require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false
