language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

env:
  global:
    - "RAILS_ENV=test"
    - secure: "ENHQ4ycah+gUibR9UQyxBggmp9NejvEmEjFfh3Tn4B9VWGMqLiJ1nDj1QsvOD0vwM1ZgxrLbWBSah8P3D7RZ/Xc410lSC8f6DpI20tmh4ATAqOvfeeNPtURuIuf+zS+CEgeXM6L6XVhF0EeheOrBURIyt54SQnt84mpWTr+Dqhk="

services:
  - postgresql

before_install:
  - gem install rubygems-update --no-document && update_rubygems
  - gem install -v 2.0.2 bundler --no-document

install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn

before_script:
  - RAILS_ENV=test rake db:setup db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  #- ./cc-test-reporter before-build

script:
  - bundle exec rubocop -DESP
  - bundle exec rake

after_script:
  #- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.simplecov.json coverage/.resultset.json
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
