language: ruby
cache:
  - bundler
  - yarn

env:
  - "RAILS_ENV=test"

before_install:
  - gem install -v 2.0.2 bundler --no-document --no-rdoc --no-ri

before_script:
  - RAILS_ENV=test rake db:create db:migrate
